module.exports = [
	{ name: "AC" },
	{ name: "+/-" },
	{ name: "%" },
	{ name: "÷", color: "#FFA500" },
	{ name: "7" },
	{ name: "8" },
	{ name: "9" },
	{ name: "x", color: "#FFA500" },
	{ name: "4" },
	{ name: "5" },
	{ name: "6" },
	{ name: "-", color: "#FFA500" },
	{ name: "1" },
	{ name: "2" },
	{ name: "3" },
	{ name: "+", color: "#FFA500" },
	{ name: "0", wide: true },
	{ name: "." },
	{ name: "=", color: "#FFA500" },
];