module.exports = [
	{ name: "AC" },
	{ name: "+/-" },
	{ name: "%" },
	{ name: "÷", orange: true },
	{ name: "7" },
	{ name: "8" },
	{ name: "9" },
	{ name: "x", orange: true },
	{ name: "4" },
	{ name: "5" },
	{ name: "6" },
	{ name: "-", orange: true },
	{ name: "1" },
	{ name: "2" },
	{ name: "3" },
	{ name: "+", orange: true },
	{ name: "0", wide: true },
	{ name: "." },
	{ name: "=", orange: true},
];